const fs = require("fs");
const path = require("path");
const vm = require("vm");
const assert = require("assert");

const root = path.join(__dirname, "..");
function loadExport() {
  const ctx = vm.createContext({ console });
  const file = path.join(root, "core", "export.js");
  if (fs.existsSync(file)) vm.runInContext(fs.readFileSync(file, "utf8"), ctx, { filename: "core/export.js" });
  return { ctx, get: (expr) => vm.runInContext(expr, ctx) };
}
let passed = 0;
function test(name, fn) { try { fn(); passed++; console.log("ok  - " + name); } catch (e) { console.error("FAIL- " + name + "\n" + e.stack); process.exitCode = 1; } }

test("Export.buildMatrix preserves plain column text and records export metadata", () => {
  const { ctx, get } = loadExport();
  assert.strictEqual(get("typeof Export"), "object");
  ctx.config = {
    title: "Wages & Payments",
    columns: [{ label: "Labour", text: (r) => r.name }, { label: "Remarks", text: (r) => r.remarks }],
    rows: [{ name: "<Suresh>", remarks: "A & B" }],
    filtersText: "Site: Alpha",
    generatedBy: "Sunita",
    now: new Date("2026-09-20T08:30:00Z"),
  };
  const matrix = JSON.parse(get("JSON.stringify(Export.buildMatrix(config))"));
  assert.deepStrictEqual(matrix, {
    title: "Wages & Payments",
    head: ["Labour", "Remarks"],
    body: [["<Suresh>", "A & B"]],
    meta: ["Generated by: Sunita", "Generated: 2026-09-20", "Filters: Site: Alpha"],
  });
});

test("Export.toCsv RFC4180-quotes commas, quotes, and newlines with a BOM", () => {
  const { ctx, get } = loadExport();
  assert.strictEqual(get("typeof Export"), "object");
  ctx.matrix = { title: "Example", head: ["Name", "Notes"], body: [["A, B", 'He said "yes"'], ["Line", "one\ntwo"]], meta: [] };
  assert.strictEqual(get("Export.toCsv(matrix)"), "\ufeffName,Notes\r\n\"A, B\",\"He said \"\"yes\"\"\"\r\nLine,\"one\ntwo\"");
});

test("Export.fileName slugifies the base name and uses the supplied date", () => {
  const { ctx, get } = loadExport();
  assert.strictEqual(get("typeof Export"), "object");
  assert.strictEqual(get("Export.fileName('Wages & Payments', 'xlsx', new Date('2026-09-20T08:30:00Z'))"), "wages-payments-2026-09-20.xlsx");
});

console.log(passed + " passed");
