/* Export helpers. Matrix creation is DOM-free; download libraries load only on demand. */
const Export = (() => {
  const scriptLoads = new Map();
  const api = {
    _urls: {
      xlsx: "https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.18.5/xlsx.full.min.js",
      jspdf: "https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js",
      autotable: "https://cdnjs.cloudflare.com/ajax/libs/jspdf-autotable/3.5.31/jspdf.plugin.autotable.min.js",
    },
  };

  function dateStamp(now) {
    const d = now instanceof Date ? now : new Date(now || Date.now());
    const pad = (n) => String(n).padStart(2, "0");
    return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}`;
  }

  function buildMatrix({ title, columns, rows, filtersText, generatedBy, now } = {}) {
    const cols = Array.isArray(columns) ? columns : [];
    const data = Array.isArray(rows) ? rows : [];
    const meta = [];
    if (generatedBy) meta.push(`Generated by: ${String(generatedBy)}`);
    meta.push(`Generated: ${dateStamp(now)}`);
    if (filtersText) meta.push(`Filters: ${String(filtersText)}`);
    return {
      title: String(title || "Export"),
      head: cols.map((column) => String(column.label ?? "")),
      body: data.map((row) => cols.map((column) => String(column.text ? column.text(row) ?? "" : ""))),
      meta,
    };
  }

  function csvCell(value) {
    const text = String(value ?? "");
    return /[",\r\n]/.test(text) ? `"${text.replace(/"/g, '""')}"` : text;
  }

  function toCsv(matrix) {
    const lines = [matrix.head || [], ...(matrix.body || [])].map((row) => row.map(csvCell).join(","));
    return `\ufeff${lines.join("\r\n")}`;
  }

  function fileName(base, ext, now) {
    const slug = String(base || "export").normalize("NFKD").replace(/[\u0300-\u036f]/g, "")
      .toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "") || "export";
    return `${slug}-${dateStamp(now)}.${String(ext || "csv").replace(/^\./, "")}`;
  }

  function notify(text) {
    if (typeof window === "undefined") return;
    if (typeof window.showToastText === "function") window.showToastText(text);
    else if (typeof window.showToast === "function") window.showToast(text, true);
  }

  function download(blob, name) {
    if (typeof document === "undefined") return;
    const href = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = href;
    link.download = name;
    link.style.display = "none";
    document.body.appendChild(link);
    link.click();
    link.remove();
    setTimeout(() => URL.revokeObjectURL(href), 0);
  }

  function loadScript(url) {
    if (scriptLoads.has(url)) return scriptLoads.get(url);
    const promise = new Promise((resolve, reject) => {
      if (typeof document === "undefined") { reject(new Error("Document unavailable")); return; }
      const existing = [...document.scripts].find((script) => script.src === url);
      if (existing && existing.dataset.exportLoaded === "true") { resolve(); return; }
      const script = existing || document.createElement("script");
      script.async = true;
      script.src = url;
      script.onload = () => { script.dataset.exportLoaded = "true"; resolve(); };
      script.onerror = () => reject(new Error(`Could not load ${url}`));
      if (!existing) document.head.appendChild(script);
    });
    scriptLoads.set(url, promise);
    promise.catch(() => scriptLoads.delete(url));
    return promise;
  }

  function matrixRows(matrix) {
    return [[matrix.title], ...(matrix.meta || []).map((line) => [line]), [], matrix.head || [], ...(matrix.body || [])];
  }

  function toExcel(matrix, baseName) {
    return loadScript(api._urls.xlsx).then(() => {
      const XLSX = window.XLSX;
      if (!XLSX) throw new Error("SheetJS unavailable");
      const sheet = XLSX.utils.aoa_to_sheet(matrixRows(matrix));
      const book = XLSX.utils.book_new();
      XLSX.utils.book_append_sheet(book, sheet, "Report");
      XLSX.writeFile(book, fileName(baseName, "xlsx"));
    }).catch(() => {
      download(new Blob([toCsv(matrix)], { type: "text/csv;charset=utf-8" }), fileName(baseName, "csv"));
      notify("Excel library unavailable — downloaded CSV");
    });
  }

  function html(value) {
    return String(value ?? "").replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]));
  }

  function printableHtml(matrix) {
    const head = (matrix.head || []).map((cell) => `<th>${html(cell)}</th>`).join("");
    const body = (matrix.body || []).map((row) => `<tr>${row.map((cell) => `<td>${html(cell)}</td>`).join("")}</tr>`).join("");
    return `<!doctype html><html><head><title>${html(matrix.title)}</title><style>body{font:12px Arial;padding:24px}h1{font-size:20px}.meta{color:#555;margin:4px 0}table{border-collapse:collapse;width:100%;margin-top:16px}th,td{border:1px solid #bbb;padding:6px;text-align:left}th{background:#eee}</style></head><body><h1>${html(matrix.title)}</h1>${(matrix.meta || []).map((line) => `<div class="meta">${html(line)}</div>`).join("")}<table><thead><tr>${head}</tr></thead><tbody>${body}</tbody></table></body></html>`;
  }

  function printFallback(matrix) {
    const printable = typeof window !== "undefined" ? window.open("", "_blank") : null;
    if (printable) {
      printable.document.open();
      printable.document.write(printableHtml(matrix));
      printable.document.close();
      printable.focus();
      printable.print();
    } else if (typeof window !== "undefined") window.print();
    notify("PDF library unavailable — opened printable view");
  }

  function toPdf(matrix, baseName) {
    return loadScript(api._urls.jspdf).then(() => loadScript(api._urls.autotable)).then(() => {
      const JsPdf = window.jspdf && window.jspdf.jsPDF;
      if (!JsPdf) throw new Error("jsPDF unavailable");
      const doc = new JsPdf({ orientation: (matrix.head || []).length > 6 ? "landscape" : "portrait" });
      doc.setFontSize(16);
      doc.text(String(matrix.title || "Export"), 14, 16);
      doc.setFontSize(9);
      (matrix.meta || []).forEach((line, index) => doc.text(String(line), 14, 23 + index * 5));
      const startY = 23 + (matrix.meta || []).length * 5 + 4;
      if (typeof doc.autoTable !== "function") throw new Error("AutoTable unavailable");
      doc.autoTable({ head: [matrix.head || []], body: matrix.body || [], startY, styles: { fontSize: 8 } });
      const pages = doc.getNumberOfPages();
      for (let page = 1; page <= pages; page++) {
        doc.setPage(page);
        doc.setFontSize(8);
        doc.text(`Page ${page} of ${pages}`, doc.internal.pageSize.getWidth() - 14, doc.internal.pageSize.getHeight() - 8, { align: "right" });
      }
      doc.save(fileName(baseName, "pdf"));
    }).catch(() => printFallback(matrix));
  }

  return Object.assign(api, { buildMatrix, toCsv, fileName, toExcel, toPdf, loadScript });
})();
